
services:
  - type: worker
    name: seats-aero-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
    autoDeploy: true
